### PR TITLE
TDD exercise

### PR DESCRIPTION
**Pull request by olesyash**
I was working with Rita Markovich @ritamarkovich on it, during the lecture ( for 2 hours). 
We were sitting together on all the steps of the exercise.Our team is divided to two - i'm working on python and her team in java- so she joined me in this exercise.

### CODE REVIEW

**Comment by robi-y** [comment]
Hi (also to @ritamarkovich)
I saw you were working, but not according to pair instructions (I'll reduce a little for it)
Overall nice work, some comments:
First 2 tests has similar code: a: you can refactor it into an assert method of your own. b: python has smarter mechanisms to check for existance in array (look for filter)
Is there still a failing test? Why is the last test red?

**Comment by olesyash** [comment]
@robi-y  It's strange because I see all green...

**Comment by robi-y** [comment]
Why is last commit message starting with RED? or maybe you have more commits that you did not pushed?

**Comment by olesyash** [comment]
This is my last commit
https://github.com/olesyash/TDD-Kata-FindAPerson/commit/8e321dedbe8f7286da44046b4ec46849406d2c86
But @ritamarkovich added new pull with fix for you comments

**Comment by robi-y** [comment]
Great!

**Pull request closed without merging**
